site_name: FUSD Chain Docs
site_description: FUSD Chain Technology Documentation
site_author: FUSD Chain Community
site_url: https://docs.finanscan.io
use_directory_urls: false
theme:
  name: material
  logo: assets/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: amber
    scheme: slate
    accent: yellow 
  feature:
    tabs: true
extra_css:
       - stylesheets/dark_theme.css
       - stylesheets/codehilite.css  
repo_name: FUSD
repo_url: https://github.com/

nav:
  - Home: index.md
  - FUSD Chain:
    - Introduction: smart-chain/guides/nc-intro.md
    - Concepts:
      - Consensus: smart-chain/guides/concepts/consensus.md
      - Genesis File: smart-chain/guides/concepts/genesis.md
    - Ecosystem: https://github.com/ 
    - FUSD Chain Mainnet Explorer: https://explorer.finanscan.io/
    - FUSD Chain Testnet Explorer: https://testnet-explorer.finanscan.io/
    - Wallet: smart-chain/wallet.md
  - FUSD Chain Developers:
    - General:
      - Create Wallet: smart-chain/developer/create-wallet.md
      - Smart Contract: https://solidity.readthedocs.io/en/v0.7.1/
      - Remix : https://remix.ethereum.org/
      - Web3JS: https://web3js.readthedocs.io/en/v1.2.11/
      - Truffle: https://www.trufflesuite.com/docs/teams/quickstart
    - Ecosystem: https://github.com/Bitgert/brise-chain
    - Deploy:
      - Remix: smart-chain/developer/deploy/remix.md
      - Truffle: smart-chain/developer/deploy/truffle.md
      - HardHat: smart-chain/developer/deploy/hardhat.md
    - Tools:   
      - Wallet Provider for DApps: smart-chain/wallet/arkane-developer.md
    - VOIP20 Tokens:
      - Introduction: smart-chain/developer/VOIP20.md
      - Issue Token: smart-chain/developer/issue-VOIP20.md
    - Blockchain Details:
      - FUSD Chain Fullnode: smart-chain/developer/fullnode.md      
      - RPC: smart-chain/developer/rpc.md
    - Tutorial:
      - Deploy NFT:  smart-chain/developer/VOIP721.md      
      - Local Brise Network: smart-chain/developer/deploy/local.md
  - Wallets:
    - FUSD Chain Wallet Support: smart-chain/wallet.md
  - FUSD Chain Explorer: https://explorer.finanscan.io
  - FUSD Chain Faucet: https://faucet.finanscan.io
  - The FUSD Chain Telegram Group : https://t.me/
  - Twitter: https://twitter.com/  
  - FAQ:
    - FUSD Chain FAQ:
      - General:
        - Info: faq/nc/general.md
        - FUSD Chain: faq/nc/nc.md
        - Ecosystem: faq/nc/eco.md
      - Token:
        - Intro: faq/nc/token.md
        - TC20: faq/nc/voip20.md
    - Contributing: CONTRIBUTING.md


markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.superfences
    - codehilite